Added MiGeL support

diff --git a/static-modules/oddb_org/templates/pg_create_db.sh.erb b/static-modules/oddb_org/templates/pg_create_db.sh.erb
--- a/static-modules/oddb_org/templates/pg_create_db.sh.erb
+++ b/static-modules/oddb_org/templates/pg_create_db.sh.erb
@@ -1,31 +1,25 @@
 #!/bin/bash -v
+# Niklaus Giger, ngiger@ywesee.com, June 17 2013
 
-ODDB_HOME=<%= foostatus = scope.lookupvar('ODDB_HOME') %>
 DB_NAME=<%= foostatus = scope.lookupvar('DB_NAME') %>
-DB_FILE=<%= foostatus = scope.lookupvar('DB_FILE') %>
-DB_DUMP=/opt/downloads/pg_dump.sql
-yyyy=`date -d '1 days ago' +"%Y"`
-mm=`date -d '1 days ago' +"%m"`
-dd=`date -d '1 days ago' +"%d"`
-
-cd $ODDB_HOME
-m=(dummy January February March April May June July August September October November December)
-nm=`expr $mm + 0`
+DB_DUMP=<%= foostatus = scope.lookupvar('DB_DUMP') %>
+cd /tmp
 sudo -u postgres dropdb $DB_NAME
-if [ $? -ne 0 ] ; then exit 1; fi
+
 sudo -u postgres createdb -E UTF8 -T template0 $DB_NAME
 if [ $? -ne 0 ] ; then exit 1; fi
 mkdir -p data/sql
 mkdir -p /opt/downloads
+if [ $? -ne 0 ] ; then exit 1; fi
+
 if [ ! -f $DB_DUMP ] 
 then
-  wget --quiet $DB_FILE -O $DB_DUMP
-  if [ $? -ne 0 ] ; then exit 1; fi
+  echo "Cannot find $DB_DUMP. Have look at the get_db_dumps.rb script or get it directly from"
+  exit 1
 fi
 
 sudo -u postgres psql -c 'create role apache with LOGIN;'
+sudo -u postgres psql -c "create role $DB_NAME with LOGIN;"
 
-# scp ywesee@thinpower.ywesee.com:/var/backup/thinpower/db/postgresql/${m[nm]}-$yyyy/$yyyy-$mm-$dd/22\:00-postgresql_database-$DB_NAME-backup.gz data/sql/$DB_NAME.$yyyy$mm$dd.sql.gz
-cd data/sql
-zcat $DB_DUMP | psql -U postgres $DB_NAME
+zcat $DB_DUMP | sudo -u postgres psql $DB_NAME
 if [ $? -ne 0 ] ; then exit 1; fi
